
/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * Full percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * Half percent.
   */
  static readonly HALF_PERCENT: string = '50%';

  /**
   * Font weight 500.
   */
  static readonly FONT_WEIGHT_500: number = 500;

  /**
   * Font weight 700.
   */
  static readonly FONT_WEIGHT_700: number = 700;

  /**
   * Picture detail path.
   */
  static readonly PICTURE_DETAIL_PATH :string =
    '@bundle:com.huawei.multicommunityapplication/picture/ets/pages/PictureDetail';

  /**
   * Detail page path.
   */
  static readonly DETAIL_PAGE_PATH: string = '@bundle:com.huawei.multicommunityapplication/detail/ets/pages/DetailPage';

  /**
   * Hot rank page path.
   */
  static readonly HOT_RANK_PAGE_PATH: string = '@bundle:com.huawei.multicommunityapplication/rank/ets/pages/HotRankPage';

  /**
   * Rank title List.
   */
  static readonly RANK_TITLE_LIST: string[] = ['今日热搜', '要闻热搜', '同城热搜', '娱乐热搜', '美食热搜'];

  /**
   * Device 2in1.
   */
  static readonly DEVICE_2IN1: string = '2in1';
}